apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: object-cache
  name: object-cache
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: object-cache
    spec:
      restartPolicy: "Never"
      containers:
      - name: object-cache
        command: ["/bin/sh", "-c"]
        args: 
        - mkdir /data && cp -R /root/data/haosu /data/ && cd /data/haosu && 
          unzip -q training_data.zip && unzip -q testing_data_pose.zip && unzip -q models.zip && 
          cd /root/icp/ && python3 src/object_cacher.py --cache_location /data/haosu/object_cache_all.hdf5 --use_full && 
          cp /data/haosu/object_cache_all.hdf5 /root/data/haosu/object_cache_all.hdf5
        resources:
          limits:
            cpu: "8"
            memory: "12Gi"
            # nvidia.com/gpu: 1
            ephemeral-storage: 50Gi
          requests:
            cpu: "8"
            memory: "8Gi"
            # nvidia.com/gpu: 1
            ephemeral-storage: 50Gi
        image: gitlab-registry.nautilus.optiputer.net/vivecenter-berkeley-edu/icp:latest
        volumeMounts:
        - mountPath: /root/data
          name: fs-store
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: fs-store
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            clusterNamespace: rook
            fsName: nautilusfs
            path: /half-potato
            mountUser: half-potato
            mountSecret: ceph-fs-secret
      imagePullSecrets:
      - name: regcredlp # this is the secret for you credentials to pull a private image




