apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: train-pointnet-seg
  name: train-pointnet-seg
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: train-pointnet-seg
    spec:
      restartPolicy: "Never"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: gpu-type
      #           operator: In
      #           values:
      #             - '2080Ti'
      #             - '1080Ti'
      containers:
      - name: train-pointnet-seg
        command: ["/bin/sh", "-c"]
        args: 
        - mkdir /data && apt-get install -y --no-install-recommends rsync && rsync -avr --exclude /root/data/haosu/object_cache_all.hdf5 /root/data/haosu /data/ && cd /data/haosu && 
          unzip -q training_data.zip && unzip -q testing_data_pose.zip && unzip -q models.zip && 
          cd /root/icp/ops && pip install . &&
          cd /root/icp/ && python3 src/train_mask.py --save_dir /root/data/haosu/ --epochs 500 --cache_location /data/haosu/frustrum_cache.hdf5 --max_points 60000
          # cp -R /root/data/haosu /data/ 
          # cd /root/icp/ && python3 src/train_mask.py --save_dir /root/data/haosu/ --epochs 500 --cache_location /data/haosu/frustrum_cache.hdf5 --max_points 200000
          # cd /root/icp/ && python3 src/frustrum_cacher.py --use_full && cp caches/frustrum_cache.hdf5 /root/data/haosu/ &&
        resources:
          limits:
            cpu: "8"
            memory: "12Gi"
            nvidia.com/gpu: 1
            ephemeral-storage: 120Gi
          requests:
            cpu: "8"
            memory: "8Gi"
            nvidia.com/gpu: 1
            ephemeral-storage: 120Gi
        image: gitlab-registry.nautilus.optiputer.net/vivecenter-berkeley-edu/icp:latest
        volumeMounts:
        - mountPath: /root/data
          name: fs-store
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: fs-store
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            clusterNamespace: rook
            fsName: nautilusfs
            path: /half-potato
            mountUser: half-potato
            mountSecret: ceph-fs-secret
      imagePullSecrets:
      - name: regcredlp # this is the secret for you credentials to pull a private image




